var Questions = [
    {"question":" How many computer languages are in use?",
      "option1": "2000",
      "option2": "5000",
      "option3":  "50",
      "option4":  "20",
       "answer":  "1"
    },
    {"question": "Which of these is not an early computer?",
     "option1" : "ENIAC",
     "option2" :"UNIVAC",
     "option3" :"NASA",
     "option4" :"SAGE",
    "answer"  : "3",
    },
    {"question":"Who founded Apple Computer?",
    "option1":"Stephen Fry",
    "option2":"Bill Gates",
    "option3":"Steve Jobs",
    "option4":"Stephen Hawking",
    "answer":"3",
    },
    {"question":"Which of these is not a peripheral, in computer terms?",
    "option1":" Keyboard",
    "option2":"Monitor",
    "option3":"Mouse",
    "option4":"Motherboard",
    "answers":"4",
    
    },
    {"question":"Which of the following is not one of the early “protocols,” or ways to use the Internet?",
    "option1":"Blogging",
    "option2":"Telnet",
    "option3":"Gopher",
    "option4":"FTP",
    "answer":"1",
    },
    ]
